server:
  port: 9092

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.web.servlet.WebMvcAutoConfiguration
################## Enable all the endpoints for actuator ###############
management:
  endpoints:
    web:
      exposure:
        include: "*"

################# Circuit Breaker ################   
eureka:
  client:
    eureka-server-port: 8761
    service-url:
      defaultZone: http://${registry.host:localhost}:${registry.port:8761}/eureka/
    healthcheck:
      enabled: true
  instance:
    health-check-url:http://localhost:9092/health

hystrix:
  command:
    accountService:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 500
      circuitBreaker:
        requestVolumeThreshold: 5
        errorThresholdPercentage: 50
        sleepWindowInMilliseconds: 1000
