spring:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
    
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    
  data:
    jpa:
      repositories:
        enabled: true

user:
  service:
    uri: http://user-service/user/

client:
  position:
    service:
      uri: http://client-position/positions/
