server:
  port: 9090
  
spring:
  thymeleaf:
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    check-template: true
    encoding: UTF-8
    servlet:
      content-type: text/html; charset=utf-8
    
eureka:
  client:
    eureka-server-port: 8761
    service-url:
      defaultZone: http://${registry.host:localhost}:${registry.port:8761}/eureka/
    healthcheck:
      enabled: true
  instance:
    health-check-url:http://localhost:9092/health

hystrix:
  command:
    userService:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 500
      circuitBreaker:
        requestVolumeThreshold: 5
        errorThresholdPercentage: 50
        sleepWindowInMilliseconds: 1000
