server:
  port: 9090
  
spring:
  application:
    name: user-service
    
eureka:
  client:
    eureka-server-port: 8761
    service-url:
      defaultZone: http://${registry.host:localhost}:${registry.port:8761}/eureka/
