server:
  port: 8888
  
spring:
  cloud:
    config:
      server:
        git:
          uri: /Users/pratulpatwari/Desktop/microservices/
          search-paths: configrepo/dev
          
      
      