server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: ${REPO:https://github.com/pratulpatwari/microservices}
          search-paths: configrepo/dev
#spring:
#  cloud:
#    config:
#      server:
#        git:
#          uri: /Users/pratulpatwari/microservices/
#          search-paths: configrepo/dev
          
      
#eureka:
#  client:
#    service-url:
#      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}